<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <gazebo reference="base_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo reference="right_wheel_link">
        <material>Gazebo/Grey</material>
        
    </gazebo>

    <gazebo reference="left_wheel_link">
        <material>Gazebo/Grey</material>
        
    </gazebo>

    <gazebo reference="caster_wheel_link">
        <material>Gazebo/Grey</material>
        <mu1 value="0.001" />
        <mu2 value="0.001" />
    </gazebo>
    <!-- .................................................................... -->
    <gazebo reference="caster2">
        <material>Gazebo/Grey</material>
        <mu1 value="0.001" />
        <mu2 value="0.001" />
    </gazebo>
    <!-- .................................................................... -->

    <!-- 
    <gazebo>
        <plugin name="skid_steer_drive_controller"
            filename="libgazebo_ros_skid_steer_drive.so">
            <update_rate>50</update_rate>
            <right_front_joint>right_front</right_front_joint>
            <right_rear_joint>right_rear</right_rear_joint>
            <left_front_joint>left_front</left_front_joint>
            <left_rear_joint>left_rear</left_rear_joint>
            <wheel_separation>0.45</wheel_separation>
            <wheel_diameter>0.2</wheel_diameter>
            <wheel_torque>500.0</wheel_torque>
            
            <covariance_x>0.0001</covariance_x>
            <covariance_y>0.0001</covariance_y>
            <covariance_yaw>0.01</covariance_yaw>
            <commandTopic>cmd_vel</commandTopic>

            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>
            <odometry_topic>odom</odometry_topic>
            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_footprint</robot_base_frame>
        </plugin>
    </gazebo>
     -->
    <gazebo>
        <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <update_rate>50</update_rate>
            <left_joint>base_left_wheel_joint</left_joint>
            <right_joint>base_right_wheel_joint</right_joint>
            <wheel_separation>0.45</wheel_separation>
            <wheel_diameter>0.2</wheel_diameter>

            
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>
            <odometry_topic>odom</odometry_topic>
            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_footprint</robot_base_frame>
            <!-- <joint name="base_right_wheel_joint" type="continuous">
                <parent link="base_link" />
                <child link="right_wheel_link" />
                <origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
                <axis xyz="0 1 0" />
            </joint>
            <joint name="base_left_wheel_joint" type="continuous">
                <parent link="base_link" />
                <child link="left_wheel_link" />
                <origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
                <axis xyz="0 1 0" />
            </joint> -->
        </plugin>
    </gazebo>
   
</robot>